Add adjustable styled status error pages
icapps/php-boilerplate pull request #23
Opened 2021-04-23 15:06 UTC by WebDaMa

2021-04-23 15:08 UTC, WebDaMa commented
Makkelijk te testen door:
Je kan 500 door elke code veranderen (link werkt enkel op dev)
https://127.0.0.1:8001/_error/500.html.twig

2021-04-26 07:38 UTC, sanhofman requested changes

2021-04-26 07:38 UTC, sanhofman commented on symfony/templates/bundles/TwigBundle/Exception/error404.html.twig
> +{% block message %}
Exception pages hebben niets te maken met TwigBundle, right?

We steken templates onder /bundles om bundle related templates uit te breiden of overschrijven.

=> deze kunnen beter onder general, system of status

2021-04-26 07:38 UTC, sanhofman commented on symfony/templates/error/error.html.twig
> +{# Error page for SULU Admin #}
Dit is geen Sulu related template maar gewoon een algemene error pagina. Deze zal nu nog altijd jouw custom pages vervangen lijkt me?

In dev mode kan je die testen met _error/* maar in prod/stage zal je nu altijd default error.html.twig krijgen

2021-04-26 09:21 UTC, WebDaMa commented on symfony/templates/error/error.html.twig
> +{# Error page for SULU Admin #}
Deze folder verwijderd om standaard Symfony flow te volgen, dan werkt het op Prod

2021-04-26 09:34 UTC, sanhofman approved these changes

2021-04-26 09:34 UTC, merged